### ISSUE TITLE
VD02 - Maxxicase

### ISSUE THREAD

**Issue by hhernany** [hhernany/ultraveloz#1]
Copiar o VEND-31 da Agritex para a Maxxicase

Criar novo indice (IND4) no VEND.SEL.

**Comment by thiagopereiramartinez** [comment]
Já está pronto no XMAXXICASE. Falta converter o VEND no oficial e sincronizar

**Comment by hhernany** [comment]
Enviar as alterações para o REAL.

Tirar o sistema do ar e reindexar o arquivo VEND na MAXXICASE, MAMORÉ e  GOMAGRIL.

**Comment by thiagopereiramartinez** [comment]
Já está sincronizado e convertido os arquivos.

**Comment by hhernany** [comment]
Alguns vendedores estão com mais de um código de vendedor e com nome "diferente". Em uma está o nome completo e no outro abreviado, por exemplo.

Tem que arrumar o nome no cadastro desses vendedores para ficarem iguais.

**Comment by thiagopereiramartinez** [comment]
Corrigido

**Comment by hhernany** [comment]
Criar novo índice no VEND.SEL, ordenando por VENDEDOR+LOJA.

Colocar a opção para ordenar por esse no índice no VEND-31.

Colocar o campo NOVO-VEND no VEND-05 e mostrar a informação no VEND-31.

**Comment by thiagopereiramartinez** [comment]
Já criado

**Comment by hhernany** [comment]
Criar a opção "T" - TRANSFERIR

A opção terá a seguinte função: Quando digitar a opção "T" sobre um vendedor, será solicitado um novo código de vendedor, para o qual ele será transferido.

Durante a transferência, deverá testar se esse código informado já existe em TODAS AS LOJAS, onde podem ocorrer dois casos:
**1)** Caso ele exista em qualquer uma das lojas, e o NOME do vendedor for DIFERENTE, dará a mensagem de que o vendedor já existe em outra loja.
**2)** Caso ele exista, e o nome do vendedor for o mesmo, permitirá a transferência para a loja informada.

Quando a transferência for feita, será gravado no vendedor de ORIGEM o novo código para o qual ele foi transferido. Essa informação será gravada no campo NOVO-VEND.

**Comment by thiagopereiramartinez** [comment]
Estão feitas as solicitações

**Comment by hhernany** [comment]
Estou atualizando os cadastros dos vendedores.

**Comment by hhernany** [comment]
Repassado para o Thiago. Ele está atualizar os cadastros.

**Comment by thiagopereiramartinez** [comment]
Atualizado
