### ISSUE TITLE
Copiar CL78/FO78 da Volmaq para Grupo Pneuar

### ISSUE THREAD

**Issue by thiagopereiramartinez** [hhernany/ultraveloz#11]

**Comment by thiagopereiramartinez** [comment]
Pode testar

**Comment by hhernany** [comment]
Vanderli está testando os programas.

**Comment by hhernany** [comment]
Na Pneuar não é mais utilizado o TIPO DE DOCUMENTO para contabilizar os títulos, em vez disso, é utilizada a CLASSIFICAÇÃO. Nesse caso, terá que trocar no CL78/FO78 tudo o que se refere a tipo de documento para Classificação.

**Comment by thiagopereiramartinez** [comment]
Alterado

**Comment by hhernany** [comment]
Conferido. Passei para o Vanderli.

**Comment by hhernany** [comment]
Concluído. Programas descontinuados. Serão substituídos pela opção de imprimir no CT43 e CT44.
