### ISSUE TITLE
PC10 - Agrofito

### ISSUE THREAD

**Issue by hhernany** [hhernany/ultraveloz#16]
Segundo o Fagner, as quantidades dos pedidos não estão sendo baixadas quando processa a nota fiscal.

Verificar a quantidade está baixando e se o pedido está fechando automaticamente quando a quantidade de todos os itens é zerada pelo processamento de NF.

Fazer os testes no servidor 100.

**Comment by RaphaelAmorimMarques** [comment]
Testei e o sistema funcionou como o esperado, não dando divergência de dados.

**Comment by hhernany** [comment]
Conferimos todos os casos e em nenhum deles aconteceu de o pedido não atualizar.

Mas, foram feitos dois outros ajustes:

Colocado para atualizar o saldo do pedido quando DESPROCESSAR a NF.

Mensagem para avisar se a quantidade do pedido não foi atualizada quando processar a NF. É salva a quantidade antes de chamar o programa de atualizar o pedido, e se a quantidade ainda estiver a mesma no final, significa que algum erro ocorreu. Isso vai ser útil para identificar os casos aonde não atualizar.
