### ISSUE TITLE
Cálculo de custo de reposição médio

### ISSUE THREAD

**Issue by hhernany** [hhernany/ultraveloz#23]
1º) Fazer no teste primeiramente
2º) Alterar a ordem da chave do MVES.FD. Primeiro o código do item e depois a loja.
3º) Mudar a chave do INVE.FD. Primeiro o código do item e depois a loja.
4º) Reindexar todos os ../inve/I  e ../inve/M. Aproveitar o INVE-0047 lá da Agritex.
5º) Se tudo estiver ok, então fazer o programa com as regras abaixo.
6º) Criar um objeto que será chamado pelo código do item (sem a loja).
7º) Este objeto irá ler o MVES do item **retroativamente** a partir da data de processamento da nota até o dia 01/01/2016.

**Comment by hhernany** [comment]
EST9-35
EST9-35
EST9-35
EST9-35
EST9-35
EST9-35

**Comment by hhernany** [comment]
Criar uma opção no ES04 para visualizar as notas que foram usadas para o calculo do novo preço médio.

A tela deve conter:

LOJA, NOTA, CLIENTE, NOME, DATA DE PROCESSAMENTO, QTD DO ITEM NA NF, VALOR DO ITEM NA NF.

FD

Chave
     CODI
     SEQUENCIA
Campos
     CHAVE DO INFE
     DATA DE PROCESSAMENTO
     QUANTIDADE DO ITEM
     VALOR DO ITEM NA NF
.

**Comment by thiagopereiramartinez** [comment]
Está finalizado
