### ISSUE TITLE
Campo de Razão Social da transportadora como "1"

### ISSUE THREAD

**Issue by thiagopereiramartinez** [hhernany/ultraveloz#34]
Estão colocando "1" no campo da razão social da transportadora no orçamento. Quando emite a nota dá erro. Criar um teste para ser no mínimo 2 digitos

**Comment by RaphaelAmorimMarques** [comment]
Pronto, Coloquei um teste nos programas ORC5-05 e TRA1-05, onde só deixa passar se o nome da transportadora tiver mais de 1 caracter
