### ISSUE TITLE
Savell - Importar Tabela de Preço

### ISSUE THREAD

**Issue by hhernany** [hhernany/ultraveloz#61]
Importar a tabela de preço da Savell.

Coluna N/N - Será o código de Fabricante e Descrição.
Coluna UNID - Unidade
Coluna QTD - Valor colocar na Observações (EMBALAGEM: XX - UNIDADE: XXX)

                 Deve formar uma STRING com a QTD por embalagem e a UNIDADE

Coluna Valor - Preço de Venda

**Comment by thiagopereiramartinez** [comment]
Importado a tabela
