### ISSUE TITLE
MF58 - Replicar o MF58 para todos os clientes.

### ISSUE THREAD

**Issue by hhernany** [hhernany/ultraveloz#67]
MF58 é o novo programa de adiantamentos. Os antigos serão desativados.

Tem que copiar o MF58, e cadastrar as contas 432 e 433 no MF02, igual está na BRADIESEL.

**Comment by hhernany** [comment]
1. Copiar todos os GADT
2. Copiar o MF58
3. Criar as contas 432 e 433 no MF02
4. Colocar o teste dentro do MOVF-78 para não contabilizar as contas 432 e 433
5. Criar permissões no GE05
6. Tirar os programas de adiantamentos antigos

           Remover do GE03
           Remover o sis/prog/
           Mover do sis/fontes para a pasta lixo

**Comment by RaphaelAmorimMarques** [comment]
PROCESSAR ADIANTAMENTO
ESTORNAR ADIANTAMENTO
CANCELAR ADIANTAMENTO

**Comment by RaphaelAmorimMarques** [comment]
mv MF48.COB MF49.COB MF50.COB MOVF-57.COB MOVF-58.COB MOVF-56.COB lixo/

**Comment by RaphaelAmorimMarques** [comment]
rm MF48.int MF49.int MF46.int MOVF-57.int MOVF-58.int MOVF-56.int

**Comment by RaphaelAmorimMarques** [comment]
Leomaquinas
maxxicase
mtdiesel
rodomolas
bradiesel
central
agritex
agrofito
volbens
pneuar

**Comment by RaphaelAmorimMarques** [comment]
NAO DEU

riama
volmaq
rastro

**Comment by RaphaelAmorimMarques** [comment]
Empresas pequenas - que nao fazem comtabeilidade comentar CLAC

**Comment by RaphaelAmorimMarques** [comment]
Esperando Hugo

**Comment by hhernany** [comment]
TRANSFERIDO PARA O SUPORTEUV.
