### ISSUE TITLE
Cadastrar novas permissões na transferência de estoque - VD12

### ISSUE THREAD

**Issue by hhernany** [hhernany/ultraveloz#83]
Na pneuar, devem ser cadastradas novas permissões no VD12 para a movimentação do estoque.

"I" - INCLUIR - Solicitar transferência depósito CDDE-TES1
"R" - PROCESSAR - Processar transferência depósito CDAT-TES2
"V" - RECEBER - Receber transferência depósito CDDE-TES1

.

**Comment by hhernany** [comment]
TES1-05 - SOLICITAR TRANSFERENCIA DEPOSITO CDDE-TES1
                  ALTERAR TRANSFERÊNCIA DEPOSITO CDDE-TES1
                  EXCLUIR TRANSFERENCIA DEPOSITO CDDE-TES1

TES1-08 - PROCESSAMENTO
                  PROCESSAR TRANSFERENCIA DEPOSITO CDAT-TES1

TES1-10 - RECEBIMENTO
                 RECEBER TRANSFERENCIA DEPOSITO CDDE-TES1


TES2-05 - Não deixar incluir se o CDAT-TES2 não for igual a CDAT-TES1.

.

**Comment by RaphaelAmorimMarques** [comment]
pronto
